In [16]:
# 텍스트 파일 입출력
f = open('name.txt', 'r', encoding='utf-8')
data = f.read()
print(data)
f.close()

맨유
QPR
AT마드리드
도르트문트

In [14]:
# 입력받아 쓰기
f = open('name2.txt', 'w', encoding='utf-8')
while True:
    team = input('팀: ')
    if not team:
        break
    f.write(team + '\n')
f.close()

In [ ]:
%pip install pandas openpyxl

In [2]:
import pandas as pd
df = pd.read_excel('my_grade.xlsx')
df.head()

   이름  1차 지필   2차 지필  수행1  수행2 등급
0  유비      92     88   93   95  A
1  관우      89     90   85   78  B
2  장비      71     84   67   70  C

In [10]:
import pandas as pd
df = pd.read_excel('club.xlsx')
add_df = pd.DataFrame([{
    '학번':10512,
    '이름':'김하늘',
    '학년':1,
    '동아리':'AI 연구부',
    '역할':'부원',
}])

new_df = pd.concat([df, add_df], ignore_index = True)
new_df.to_excel('new_club.xlsx', index = False)
new_df.tail()

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원
3  10512  김하늘   1  AI 연구부  부원